from restaurant_sistem.database_service.clientes import ClientesDataBase
from restaurant_sistem.database_service.empleados import EmpleadosDataBase
from restaurant_sistem.database_service.proveedores import ProveedoresDataBase
from restaurant_sistem.database_service.sedes import SedesDataBase

from restaurant_sistem.database_service.facturas import FacturasDataBase


from restaurant_sistem.statistic.clientes import metricas_cliente
from restaurant_sistem.statistic.empleados import metricas_empleados
from restaurant_sistem.statistic.sedes import metricas_sedes
from restaurant_sistem.statistic.proveedores import metricas_proveedores
from restaurant_sistem.statistic.factura import metricas_facturas
