from restaurant_sistem.database_service.clientes import ClientesDataBase
from restaurant_sistem.database_service.empleados import EmpleadosDataBase
from restaurant_sistem.database_service.empleados import EmpleadosDataBase
from restaurant_sistem.statistic.clientes import metricas_cliente
from restaurant_sistem.statistic.empleados import metricas_empleados